        name = "gnoga = { path ="/Users/Wayne/GNAT/share/gpr" }"
description = "gnoga = { path ="/Users/Wayne/GNAT/share/gpr" } Utility Library"
version = "2.0-dev"

authors = ["Wayne Bullaughey"]
maintainers = ["Wayne Bullaughey <wlb122@verizon.net>"]
maintainers-logins = ["wbullaughey"]

[[depends-on]]
applications = "*"

[[pins]]
applications  = { path = ".." }

[[depends-on]]
gnatcoll = "^23.0.0"
