name = "ada_lib"
description = "Ada_Lib Utility Library"
version = "2.0-dev"

authors = ["Wayne Bullaughey"]
maintainers = ["Wayne Bullaughey <wlb122@verizon.net>"]
maintainers-logins = ["wbullaughey"]

[[depends-on]]
gnatcoll = "^25.0.0"

[[depends-on]]
alr_environment = "*"

[[pins]]
alr_environment  = { path = ".." }


