name = "ada_lib_tests"
description = "Shiny new project"
version = "0.1.0-dev"

authors = ["Wayne Bullaughey"]
maintainers = ["Wayne Bullaughey <wlb122@verizon.net>"]
maintainers-logins = ["wbullaughey"]

executables = ["ada_lib_tests"]

[[depends-on]]
ada_lib = "*"

[[pins]]
ada_lib  = { path = "../" }

[[depends-on]]
aunit = "*"

[[pins]]
aunit  = { path = "../../aunit" }

[[depends-on]]
gnatcoll = "^23.0.0"

[[depends-on]]
gnoga = "^2.1.2"
