name = "ada_lib_tests"
description = "Shiny new project"
version = "0.1.0-dev"

authors = ["Wayne Bullaughey"]
maintainers = ["Wayne Bullaughey <wlb122@verizon.net>"]
maintainers-logins = ["wbullaughey"]

executables = ["ada_lib_tests"]

[[depends-on]]
ada_lib = "*"

[[pins]]
ada_lib  = { path = ".." }

[[depends-on]]
ada_lib_gnoga = "*"

[[pins]]
ada_lib_gnoga  = { path = "../ada_lib_gnoga" }

[[depends-on]]
aunit = "*"

[[pins]]
aunit  = { path = "../../aunit" }

[[depends-on]]
gnoga = "*"

[[pins]]
gnoga  = { path = "../../vendor/github.com/gnoga" }

[[depends-on]]
gnatcoll = "^23.0.0"

