name = "ada_lib_testing"
description = "ada_lib testing library"
version = "0.1.0-dev"

authors = ["Wayne Bullaughey"]
maintainers = ["Wayne Bullaughey <wlb122@verizon.net>"]
maintainers-logins = ["wbullaughey"]

[[depends-on]]
ada_lib = "*"

[[pins]]
ada_lib  = { path = "../" }

[[depends-on]]
aunit = "*"

[[pins]]
aunit  = { path = "../../aunit" }

[[depends-on]]
gnoga = "*"

[[pins]]
gnoga  = { path = "../../vendor/github.com/gnoga" }

[[depends-on]]
applications = "*"

[[pins]]
applications  = { path = "../.." }

